name:                whatnow
version:             1.0.0.0
author:              jefdaj
maintainer:          jefdaj@users.noreply.github.com
copyright:           "MIT"

dependencies:
  - base
  - dhall

library:
  source-dirs: src
