name:                git-kaizen
description:         Incrementally organize files and improve file-related workflows.
version:             1.0.0.0
author:              jefdaj
maintainer:          jefdaj@users.noreply.github.com
copyright:           "MIT"

data-files:
  - tests/untar/*
  - examples/*/*/*.hs

dependencies:
  - base
  - dhall
  - docopt
  - pretty-simple
  - text
  - filepath
  - ghc
  - ghc-paths
  - filepath
  - filepattern
  - split

library:
  source-dirs: lib
  exposed-modules:
  - GitKaizen.Types
  - GitKaizen.Interface

executable:
  source-dirs: app
  main: Main.hs
  dependencies:
  - git-kaizen
