name:                git-kaizen
description:         Incremental improvement of version controlled files.
version:             0.1.0.0
author:              jefdaj
maintainer:          jefdaj@users.noreply.github.com
copyright:           "AGPL-3.0-only"

data-files:
  - examples/*/kaizen.d/*.hs
  - examples/*/kaizen.d/*.sh

dependencies:
  - base
  - co-log-core
  - data-default
  - directory
  - docopt
  - filepath
  - filepath
  - filepattern
  - ghc
  - ghc-paths
  - pretty-simple
  - split
  - tasty
  - tasty-discover
  - tasty-hunit
  - tasty-quickcheck
  - text

library:
  source-dirs: lib
  exposed-modules:
  - GitKaizen.Interface
  - GitKaizen.Types

executable:
  source-dirs: app
  main: Main.hs
  dependencies:
  - git-kaizen

tests:

  test-lib:
    source-dirs:
    - "test/lib"
    - "lib"
    main: "Test.hs"
    dependencies:
    - "base"

  test-app:
    source-dirs:
    - "test/app"
    - "app"
    main: "Test.hs"
    dependencies:
    - "base"
    - "git-kaizen"
