name:                kaizen
version:             1.0.0.0
author:              jefdaj
maintainer:          jefdaj@users.noreply.github.com
copyright:           "MIT"

dependencies:
  - base
  - dhall
  - docopt

library:
  source-dirs: src
