name:                file-kaizen
description:         Incrementally organize files and improve file-related workflows.
version:             1.0.0.0
author:              jefdaj
maintainer:          jefdaj@users.noreply.github.com
copyright:           "MIT"

data-files:
  - examples/kaizen.d/*

dependencies:
  - base
  - dhall
  - docopt
  - pretty-simple
  - text

library:
  source-dirs: src
