name:                git-kaizen
description:         Incrementally organize files and improve file-related workflows.
version:             1.0.0.0
author:              jefdaj
maintainer:          jefdaj@users.noreply.github.com
copyright:           "MIT"

data-files:
  - tests/untar/*

dependencies:
  - base
  - dhall
  - docopt
  - pretty-simple
  - text
  - filepath
  - ghc
  - ghc-paths

executable:
  source-dirs: src
  main: GitKaizen.hs
