name:                git-kaizen
description:         Incrementally organize files and improve file-related workflows.
version:             1.0.0.0
author:              jefdaj
maintainer:          jefdaj@users.noreply.github.com
copyright:           "MIT"

data-files:
  - examples/*/*/*.hs

dependencies:
  - base
  - dhall
  - docopt
  - filepath
  - filepath
  - filepattern
  - ghc
  - ghc-paths
  - pretty-simple
  - split
  - tasty
  - tasty-discover
  - tasty-hunit
  - tasty-quickcheck
  - text

library:
  source-dirs: lib
  exposed-modules:
  - GitKaizen.Interface
  - GitKaizen.Types

executable:
  source-dirs: app
  main: Main.hs
  dependencies:
  - git-kaizen

tests:

  # test-lib:
  #   source-dirs: "lib"
  #   main: "Test.hs"
  #   dependencies:
  #   - "base"
  #   - "git-kaizen"

  test-lib:
    source-dirs:
    - "lib"
    - "test"
    main: "Test.hs"
    dependencies:
    - "base"
    - "git-kaizen"
