name:                kaizen
version:             1.0.0.0
author:              jefdaj
maintainer:          jefdaj@users.noreply.github.com
copyright:           "MIT"

data-files:
  - examples/kaizen.d/*

dependencies:
  - base
  - dhall
  - docopt

library:
  source-dirs: src
